# Generated by Django 4.2.7 on 2023-11-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mi_API_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='personas',
            new_name='Mi_API_rest',
        ),
    ]
